### ISSUE TITLE
README 文档有错别字

### ISSUE THREAD

**Issue by chiyuchia** [BingKui/QuillChineseDoc#1]
Quill是一个所见即所得的富文本编辑器，拥有很好的交互体验，目前在github上的

> ~~额~~

星数是编辑器中star最高的编辑器。用户可以在基础上进行自定义的开发，来完成自己的编辑器功能。

---

建议修改：

Quill是一个所见即所得的富文本编辑器，拥有很好的交互体验，目前在github上的

> ~~额~~

星数是

> 富文本

编辑器中

> ~~star~~

最高

> 的

> ~~的编辑器~~

。用户可以在基础上进行自定义的开发，来完成自己的编辑器功能。

**Comment by BingKui** [comment]
谢谢提醒，已经修改。
